from django.db import models


class jieba(models.Model):
    effect = models.CharField(max_length=20)
    number = models.DecimalField(max_digits=3,decimal_places=0)
    
class effect(models.Model):
    a = models.DecimalField(max_digits=3,decimal_places=0)
    b = models.DecimalField(max_digits=3,decimal_places=0)
    c = models.DecimalField(max_digits=3,decimal_places=0)
    d = models.DecimalField(max_digits=3,decimal_places=0)
    e = models.DecimalField(max_digits=3,decimal_places=0)

class filter_product(models.Model):
    proid= models.DecimalField(max_digits=10,decimal_places=0)
    protype= models.DecimalField(max_digits=10,decimal_places=0)
    price= models.DecimalField(max_digits=10,decimal_places=0)
    skintype= models.CharField(max_length=20)
    age_deg= models.CharField(max_length=20)
    score= models.DecimalField(max_digits=10,decimal_places=0)
    A= models.DecimalField(max_digits=3,decimal_places=0)
    B= models.DecimalField(max_digits=3,decimal_places=0)
    C= models.DecimalField(max_digits=3,decimal_places=0)
    D= models.DecimalField(max_digits=3,decimal_places=0)
    E= models.DecimalField(max_digits=3,decimal_places=0)
    F= models.DecimalField(max_digits=3,decimal_places=0)
    G= models.DecimalField(max_digits=3,decimal_places=0)
    H= models.DecimalField(max_digits=3,decimal_places=0)
    I= models.DecimalField(max_digits=3,decimal_places=0)
    J= models.DecimalField(max_digits=3,decimal_places=0)
    K= models.DecimalField(max_digits=3,decimal_places=0)
    L= models.DecimalField(max_digits=3,decimal_places=0)
    M= models.DecimalField(max_digits=3,decimal_places=0)
    N= models.DecimalField(max_digits=3,decimal_places=0)
    O= models.DecimalField(max_digits=3,decimal_places=0)
    P= models.DecimalField(max_digits=3,decimal_places=0)
    Q= models.DecimalField(max_digits=3,decimal_places=0)
    R= models.DecimalField(max_digits=3,decimal_places=0)
    S= models.DecimalField(max_digits=3,decimal_places=0)
    T= models.DecimalField(max_digits=3,decimal_places=0)
    U= models.DecimalField(max_digits=3,decimal_places=0)
    V= models.DecimalField(max_digits=3,decimal_places=0)
    W= models.DecimalField(max_digits=3,decimal_places=0)
    X= models.DecimalField(max_digits=3,decimal_places=0)
    Y= models.DecimalField(max_digits=3,decimal_places=0)
    Z= models.DecimalField(max_digits=3,decimal_places=0)
    AA= models.DecimalField(max_digits=3,decimal_places=0)
    AB= models.DecimalField(max_digits=3,decimal_places=0)
    AC= models.DecimalField(max_digits=3,decimal_places=0)
    AD= models.DecimalField(max_digits=3,decimal_places=0)
    AE= models.DecimalField(max_digits=3,decimal_places=0)
    AF= models.DecimalField(max_digits=3,decimal_places=0)
    AG= models.DecimalField(max_digits=3,decimal_places=0)
    AH= models.DecimalField(max_digits=3,decimal_places=0)
    AI= models.DecimalField(max_digits=3,decimal_places=0)
    AJ= models.DecimalField(max_digits=3,decimal_places=0)
    AK= models.DecimalField(max_digits=3,decimal_places=0)
    AL= models.DecimalField(max_digits=3,decimal_places=0)
    AM= models.DecimalField(max_digits=3,decimal_places=0)
    AN= models.DecimalField(max_digits=3,decimal_places=0)
    AO= models.DecimalField(max_digits=3,decimal_places=0)
    AP= models.DecimalField(max_digits=3,decimal_places=0)
    AQ= models.DecimalField(max_digits=3,decimal_places=0)
    AR= models.DecimalField(max_digits=3,decimal_places=0)
    AS= models.DecimalField(max_digits=3,decimal_places=0)
    AT= models.DecimalField(max_digits=3,decimal_places=0)
    AU= models.DecimalField(max_digits=3,decimal_places=0)
    AV= models.DecimalField(max_digits=3,decimal_places=0)
    AW= models.DecimalField(max_digits=3,decimal_places=0)
    AX= models.DecimalField(max_digits=3,decimal_places=0)
    AY= models.DecimalField(max_digits=3,decimal_places=0)
    AZ= models.DecimalField(max_digits=3,decimal_places=0)
    BA= models.DecimalField(max_digits=3,decimal_places=0)
    BB= models.DecimalField(max_digits=3,decimal_places=0)
    BC= models.DecimalField(max_digits=3,decimal_places=0)
    BD= models.DecimalField(max_digits=3,decimal_places=0)
    BE= models.DecimalField(max_digits=3,decimal_places=0)
    BF= models.DecimalField(max_digits=3,decimal_places=0)
    BG= models.DecimalField(max_digits=3,decimal_places=0)
    rebuy= models.DecimalField(max_digits=10,decimal_places=0)
    effsum= models.DecimalField(max_digits=10,decimal_places=0)
    weights= models.DecimalField(max_digits=20,decimal_places=15)
    score_new= models.DecimalField(max_digits=20,decimal_places=15)
    counts= models.DecimalField(max_digits=10,decimal_places=0) 